version: "3"

services:
  api:
    build: ./api
    container_name: api
    restart: always
    volumes:
      - ./api/:/app
    expose:
      - 9000

  ui:
    build: ui
    container_name: ui
    restart: always
    ports:
      - "8000:80"