version: "3"

services:
  api:
    build: ./api
    container_name: api
    restart: always
    volumes:
      - ./api/:/app
    expose:
      - 9000

  ui:
    build:
      context: ui/
      dockerfile: ui/Dockerfile
    container_name: ui
    restart: always
    ports:
      - "8000:80"
    volumes:
      - ./ui/nginx.conf:/etc/nginx/nginx.conf:ro
    links:
      - api